DELETE http://localhost:3001/api/persons/2

###

GET http://localhost:3001/api/persons/6a992dcca449f92ec7992697

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test Person",
  "number": "123-456789"
}

###
GET http://localhost:3001/api/persons/64